using System;
using Terminal.Gui;
using System.IO;
namespace Proyecto_Juego;

public class Events
{
    static string[] EventosEconomicos = new string[]
{
    // ECONOMÍA GLOBAL (AFECTAN A TODAS LAS EMPRESAS9
    "CRISIS_GLOBAL_INFLACION",
    "BOOM_ECONOMICO_MUNDIAL",
    "RECESION_INTERNACIONAL",
    "CAIDA_MERCADOS_BURSATILES",
    "RECUPERACION_POST_CRISIS",
    "SUBIDA_PRECIO_PETROLEO",
    "CAIDA_PRECIO_PETROLEO",
    "ESCACEZ_MATERIAS_PRIMAS",
    "AUMENTO_DEMANDA_GLOBAL",
    "CONTRACCION_COMERCIO_MUNDIAL",

    // POLÍTICA / ESTADO
    "CAMBIO_GOBIERNO_ESTABLE",
    "CAMBIO_GOBIERNO_INESTABLE",
    "GOLPE_DE_ESTADO",
    "REFORMA_FISCAL_POSITIVA",
    "REFORMA_FISCAL_NEGATIVA",
    "AUMENTO_IMPUESTOS",
    "REDUCCION_IMPUESTOS",
    "ESTABILIDAD_POLITICA",
    "CRISIS_POLITICA_INTERNA",
    "PROTESTAS_MASIVAS",

    // ECONOMÍA LOCAL (SOLO AFECTAN A LAS EMPRESAS DEL PAIS DEL JUGADOR9
    "AUMENTO_PIB",
    "CAIDA_PIB",
    "INFLACION_CONTROLADA",
    "HIPERINFLACION",
    "DEVALUACION_MONEDA",
    "REVALUACION_MONEDA",
    "AUMENTO_CONSUMO_INTERNO",
    "CAIDA_CONSUMO_INTERNO",

    // EMPRESAS / MERCADO
    "BOOM_BURSATIL",
    "COLAPSO_BURSATIL",
    "QUIEBRA_EMPRESA_GRANDE",
    "FUSIONES_EMPRESARIALES",
    "INVERSION_EXTRANJERA",
    "RETIRADA_INVERSIONES",
    "AUMENTO_ACCIONES",
    "CAIDA_ACCIONES",
    "ESCANDALO_CORPORATIVO",
    "MONOPOLIO_SECTORIAL",

    // 🧠 TECNOLOGÍA
    "INNOVACION_TECNOLOGICA",
    "AVANCE_INTELIGENCIA_ARTIFICIAL",
    "OBSOLESCENCIA_SECTORIAL",
    "AUTOMATIZACION_MASIVA",
    "CIBERATAQUE_EMPRESARIAL",
    "FUGA_DE_DATOS",

    // 🏭 INDUSTRIA / SECTORES
    "CRECIMIENTO_SECTOR_TECNOLOGICO",
    "CRISIS_SECTOR_ENERGETICO",
    "EXPANSION_AGRICOLA",
    "CAIDA_PRODUCCION_MANUFACTURERA",
    "AUGE_TURISMO",
    "CAIDA_TURISMO",
    "DEMANDA_CONSTRUCCION_ALTA",
    "CRISIS_INMOBILIARIA",

    // 🌾 AGRICULTURA / RECURSOS
    "SEQUIA_PROLONGADA",
    "BUENA_COSECHA",
    "PERDIDA_CULTIVOS",
    "SUBIDA_PRECIO_ALIMENTOS",
    "ESCACEZ_AGUA",

    // ⚔️ EVENTOS DRÁSTICOS
    "GUERRA_REGIONAL",
    "TRATADO_COMERCIAL",
    "SANCIONES_INTERNACIONALES",
    "BLOQUEO_ECONOMICO",
    "ACUERDO_DE_LIBRE_COMERCIO",

    // 🧍 SOCIEDAD / HUMANOS
    "AUMENTO_CARISMA_LIDERES",
    "CAIDA_CONFIANZA_PUBLICA",
    "MIGRACION_MASIVA",
    "FUGA_DE_CEREBROS",
    "CRECIMIENTO_EDUCACION",
    "CRISIS_SANITARIA",

    // 🎲 RANDOM ABSURDO (porque la economía también lo es)
    "CAFE_SE_VUELVE_RESERVA_MUNDIAL",
    "MEME_STOCK_EXPLOTA",
    "CEO_HUYE_AL_ESPACIO",
    "ERROR_MERCADO_SIMULACION",
    "INVERSION_EN_PAPAS_RINDE_300%",
    "INFLACION_POR_RUMOR_EN_TWITTER"
};
    static void Periodico(Toplevel top)
    {
        var VentanaPeriodico = new Window()
        {
            X = 0,
            Y = 0,
            Width = Dim.Fill(),
            Height = Dim.Fill(),
        };

        top.Add(VentanaPeriodico);
    }
}
